---
- name: General infrastructure
  hosts: all
  become: true
  tasks:
    - name: Update apt
      apt: update_cache=yes cache_valid_time=86400
    - name: Install packages
      apt: pkg={{item}} state=installed
      with_items:
        - git
        - vim
        - unzip
        - ntp
        - samba

- name: Install Java and Bluetooth stack on Raspberry
  hosts: raspberry
  become: true
  tasks:
    - name: Install Java 8 JDK
      apt: pkg=oracle-java8-jdk state=present
    - name: Install Bluetooth
      apt: pkg=bluez state=present


- name: Install Java and set timezone on Vagrant Debian
  hosts: vagrant
  become: true
  roles:
    -  williamyeh.oracle-java
  tasks:
    - name: Set timezone
      copy: dest=/etc/timezone content={{ timezone }}

# Inlcuded playbook is also for Vagrant debian
- include: tasks/install_influxdb_debian.yml

