---
# TODO Make install dependent on machine architecture: vagrant machine vs raspbian 
- hosts: all
  roles: 
    - williamyeh.oracle-java # This is vagrant-specific
  vars:
    - java_version: 8
    - java_remove_download: false
  tasks:
    - name: Update apt
      apt: update_cache=yes cache_valid_time=86400
    - name: Install packages
      apt: pkg={{item}} state=installed
      with_items:
        - git
        - vim
        - unzip
        - ntp
        - samba
    # TODO: set hostname
    # TODO: Set timezone

- include: tasks/install_influxdb_debian.yml

