---
- name: General infrastructure
  hosts: all
  become: true
  tasks:
    - name: Update apt
      apt: update_cache=yes cache_valid_time=86400
    - name: Install packages
      apt: pkg={{item}} state=installed
      with_items:
        - git
        - vim
        - unzip
        - ntp
        - samba


# Here comes the Vagrant-Specific part

- name: Install Java and set timezone
  hosts: vagrant
  become: true
  roles:
    -  williamyeh.oracle-java
  tasks:
    - name: Set timezone
      copy: dest=/etc/timezone content={{ timezone }}

- include: tasks/install_influxdb_debian.yml

