---
- hosts: all
  tasks:
    - name: Update apt
      apt: update_cache=yes cache_valid_time=86400
    - name: Install packages
      apt: pkg={{item}} state=installed
      items:
        - vim
        - mysql
