---
- hosts: vagrant
  name: Install InfluxDB
  become: true
  vars: 
    influxdb_download_dir: /home/vagrant/downloads
    influxdb_package_name: influxdb
    influxdb_package_url: https://s3.amazonaws.com/influxdb/influxdb_0.9.6.1_amd64.deb
  tasks:
    - name: Check if my_package is installed
      command: dpkg-query -W {{ influxdb_package_name }}
      register: influxdb_check_deb
      failed_when: influxdb_check_deb.rc > 1
      changed_when: influxdb_check_deb.rc == 1
    - name: Create download dir
      file: name={{ influxdb_download_dir }} state=directory
      when: influxdb_check_deb.rc == 1
    - name: Download influxdb deb
      get_url: url={{ influxdb_package_url }} dest={{ influxdb_download_dir }}/{{ influxdb_package_url|basename }}
      when: influxdb_check_deb.rc == 1
    - name: Install influxdb
      apt: deb={{ influxdb_download_dir }}/{{ influxdb_package_url|basename }} state=present
      become: true
      when: influxdb_check_deb.rc == 1
